# Generated by Django 5.2.8 on 2025-12-01 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Punjab", "Punjab"),
                            ("Sindh", "Sindh"),
                            ("Khyber Pakhtunkhwa", "Khyber Pakhtunkhwa"),
                            ("Balochistan", "Balochistan"),
                            (
                                "Islamabad Capital Territory",
                                "Islamabad Capital Territory",
                            ),
                            ("Gilgit-Baltistan", "Gilgit-Baltistan"),
                            ("Azad Jammu and Kashmir", "Azad Jammu and Kashmir"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total population from WorldPop grid",
                        null=True,
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["province", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="air_quality_name_1e56d2_idx"),
                    models.Index(
                        fields=["province"], name="air_quality_provinc_9a21aa_idx"
                    ),
                ],
                "unique_together": {("name", "province")},
            },
        ),
        migrations.CreateModel(
            name="GroundStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openaq_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("openaq_location_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Pakistan", max_length=50)),
                (
                    "available_parameters",
                    models.JSONField(
                        default=list,
                        help_text="List of pollutants measured at this station",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ground_stations",
                        to="air_quality.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Station",
                "verbose_name_plural": "Ground Stations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PollutantRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "raw_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to raw downloaded raster",
                        max_length=500,
                    ),
                ),
                (
                    "corrected_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to bias-corrected raster",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOWNLOADING", "Downloading"),
                            ("DOWNLOADED", "Downloaded"),
                            ("CORRECTING", "Applying Correction"),
                            ("CORRECTED", "Corrected"),
                            ("CALCULATING", "Calculating Exposure"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "correction_model_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the correction model used",
                        null=True,
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("mean_value", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("corrected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pollutant Raster",
                "verbose_name_plural": "Pollutant Rasters",
                "ordering": ["-date", "pollutant"],
                "indexes": [
                    models.Index(fields=["date"], name="air_quality_date_e7630f_idx"),
                    models.Index(
                        fields=["pollutant"], name="air_quality_polluta_bef61c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="air_quality_status_8ed389_idx"
                    ),
                    models.Index(
                        fields=["date", "pollutant"], name="air_quality_date_2976f8_idx"
                    ),
                ],
                "unique_together": {("date", "pollutant")},
            },
        ),
        migrations.CreateModel(
            name="GroundReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "no2",
                    models.FloatField(blank=True, help_text="NO2 in ppb", null=True),
                ),
                (
                    "so2",
                    models.FloatField(blank=True, help_text="SO2 in ppb", null=True),
                ),
                (
                    "pm25",
                    models.FloatField(
                        blank=True, help_text="PM2.5 in µg/m³", null=True
                    ),
                ),
                ("co", models.FloatField(blank=True, help_text="CO in ppm", null=True)),
                ("o3", models.FloatField(blank=True, help_text="O3 in ppb", null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="air_quality.groundstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Reading",
                "verbose_name_plural": "Ground Readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="air_quality_timesta_39747d_idx"
                    ),
                    models.Index(
                        fields=["station", "timestamp"],
                        name="air_quality_station_471b74_idx",
                    ),
                ],
                "unique_together": {("station", "timestamp")},
            },
        ),
    ]
