# Generated by Django 4.2 on 2025-12-04 16:40

import air_quality.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQualityStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openaq_location_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Unique location ID from OpenAQ API",
                        unique=True,
                    ),
                ),
                (
                    "openaq_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Legacy string ID (deprecated, use openaq_location_id)",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Latitude in decimal degrees (WGS84)",
                        validators=[air_quality.models.validate_latitude],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Longitude in decimal degrees (WGS84)",
                        validators=[air_quality.models.validate_longitude],
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Auto-populated Point geometry",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text="Locality/neighborhood name",
                        max_length=200,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="PK", max_length=50)),
                ("timezone", models.CharField(default="Asia/Karachi", max_length=50)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("OPENAQ", "OpenAQ API"),
                            ("MANUAL", "Manual Entry"),
                            ("GOV", "Government Agency"),
                            ("RESEARCH", "Research Institution"),
                        ],
                        default="OPENAQ",
                        max_length=20,
                    ),
                ),
                (
                    "available_parameters",
                    models.JSONField(
                        default=list,
                        help_text="List of pollutants measured at this station",
                    ),
                ),
                (
                    "sensors_count",
                    models.IntegerField(
                        default=0, help_text="Number of sensors at this station"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Critical (hourly sync)"),
                            (2, "High (daily sync)"),
                            (3, "Medium (weekly sync)"),
                            (4, "Low (monthly sync)"),
                            (5, "Minimal (on-demand only)"),
                        ],
                        db_index=True,
                        default=3,
                        help_text="Priority for API queries (1=highest)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether station is included in regular syncs",
                    ),
                ),
                (
                    "last_reading_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent reading",
                        null=True,
                    ),
                ),
                (
                    "total_readings",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of readings from this station",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Air Quality Station",
                "verbose_name_plural": "Air Quality Stations",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="DataIngestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial Success"),
                        ],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="openaq_bulk",
                        help_text="Type of data source (openaq_bulk, openaq_api, manual)",
                        max_length=50,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to source files or API endpoint",
                        max_length=500,
                    ),
                ),
                ("files_processed", models.IntegerField(default=0)),
                ("records_total", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_skipped", models.IntegerField(default=0)),
                ("records_invalid", models.IntegerField(default=0)),
                ("stations_processed", models.IntegerField(default=0)),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Total processing time in seconds",
                        null=True,
                    ),
                ),
                ("error_count", models.IntegerField(default=0)),
                (
                    "error_log_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to detailed error log file",
                        max_length=500,
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True, help_text="Summary of errors encountered"
                    ),
                ),
                (
                    "command_args",
                    models.JSONField(
                        default=dict,
                        help_text="Arguments passed to the ingestion command",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Ingestion Log",
                "verbose_name_plural": "Data Ingestion Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total population from WorldPop grid",
                        null=True,
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="groundreading",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Ground Reading (Legacy)",
                "verbose_name_plural": "Ground Readings (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="groundstation",
            options={
                "ordering": ["name"],
                "verbose_name": "Ground Station (Legacy)",
                "verbose_name_plural": "Ground Stations (Legacy)",
            },
        ),
        migrations.AlterField(
            model_name="pollutantraster",
            name="pollutant",
            field=models.CharField(
                choices=[
                    ("NO2", "NO2"),
                    ("SO2", "SO2"),
                    ("PM25", "PM25"),
                    ("PM10", "PM10"),
                    ("PM1", "PM1"),
                    ("CO", "CO"),
                    ("O3", "O3"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Tehsil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Punjab", "Punjab"),
                            ("Sindh", "Sindh"),
                            ("Khyber Pakhtunkhwa", "Khyber Pakhtunkhwa"),
                            ("Balochistan", "Balochistan"),
                            (
                                "Islamabad Capital Territory",
                                "Islamabad Capital Territory",
                            ),
                            ("Gilgit-Baltistan", "Gilgit-Baltistan"),
                            ("Azad Jammu and Kashmir", "Azad Jammu and Kashmir"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total population from WorldPop grid",
                        null=True,
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tehsils",
                        to="air_quality.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tehsil",
                "verbose_name_plural": "Tehsils",
                "ordering": ["province", "district", "name"],
            },
        ),
        migrations.CreateModel(
            name="PollutantReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Measurement timestamp (UTC)"
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("PM10", "PM10"),
                            ("PM1", "PM1"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        help_text="Pollutant type (e.g., PM25, NO2)",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.FloatField(help_text="Measurement value in original units"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("µg/m³", "UG_M3"),
                            ("mg/m³", "MG_M3"),
                            ("ng/m³", "NG_M3"),
                            ("ppm", "PPM"),
                            ("ppb", "PPB"),
                            ("ppmv", "PPMV"),
                            ("mol/m²", "MOL_M2"),
                            ("molecules/cm²", "MOLEC_CM2"),
                            ("DU", "DU"),
                            ("particles/cm³", "PARTICLES_CM3"),
                            ("#/cm³", "COUNT_CM3"),
                            ("index", "INDEX"),
                            ("", "UNITLESS"),
                        ],
                        help_text="Original measurement unit",
                        max_length=20,
                    ),
                ),
                (
                    "value_normalized",
                    models.FloatField(
                        blank=True,
                        help_text="Value normalized to standard unit (µg/m³ for most)",
                        null=True,
                    ),
                ),
                (
                    "unit_normalized",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("µg/m³", "UG_M3"),
                            ("mg/m³", "MG_M3"),
                            ("ng/m³", "NG_M3"),
                            ("ppm", "PPM"),
                            ("ppb", "PPB"),
                            ("ppmv", "PPMV"),
                            ("mol/m²", "MOL_M2"),
                            ("molecules/cm²", "MOLEC_CM2"),
                            ("DU", "DU"),
                            ("particles/cm³", "PARTICLES_CM3"),
                            ("#/cm³", "COUNT_CM3"),
                            ("index", "INDEX"),
                            ("", "UNITLESS"),
                        ],
                        help_text="Standard unit after normalization",
                        max_length=20,
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether reading passed validation checks",
                    ),
                ),
                (
                    "validation_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation issues (e.g., ['out_of_range', 'negative'])",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Original data from API/file", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="air_quality.airqualitystation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pollutant Reading",
                "verbose_name_plural": "Pollutant Readings",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="dataingestionlog",
            index=models.Index(
                fields=["started_at"], name="air_quality_started_81f5af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataingestionlog",
            index=models.Index(fields=["status"], name="air_quality_status_a5f136_idx"),
        ),
        migrations.AddIndex(
            model_name="dataingestionlog",
            index=models.Index(
                fields=["source_type"], name="air_quality_source__47f866_idx"
            ),
        ),
        migrations.AddField(
            model_name="airqualitystation",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="air_quality_stations",
                to="air_quality.district",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tehsil",
            unique_together={("name", "district")},
        ),
        migrations.AddIndex(
            model_name="pollutantreading",
            index=models.Index(
                fields=["timestamp"], name="air_quality_timesta_2fef60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollutantreading",
            index=models.Index(
                fields=["parameter"], name="air_quality_paramet_886c62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollutantreading",
            index=models.Index(
                fields=["station", "timestamp"], name="air_quality_station_764d67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollutantreading",
            index=models.Index(
                fields=["station", "parameter", "timestamp"],
                name="air_quality_station_2ea266_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pollutantreading",
            index=models.Index(
                fields=["is_valid"], name="air_quality_is_vali_cfd8ae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pollutantreading",
            unique_together={("station", "timestamp", "parameter")},
        ),
        migrations.AddIndex(
            model_name="airqualitystation",
            index=models.Index(
                fields=["openaq_location_id"], name="air_quality_openaq__e6d761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airqualitystation",
            index=models.Index(
                fields=["is_active", "priority"], name="air_quality_is_acti_89cb0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airqualitystation",
            index=models.Index(
                fields=["country"], name="air_quality_country_d97c62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airqualitystation",
            index=models.Index(
                fields=["data_source"], name="air_quality_data_so_69f47e_idx"
            ),
        ),
    ]
