# Generated by Django 4.2 on 2025-12-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality", "0002_add_new_station_reading_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("S5P_NO2", "Sentinel-5P NO2 Latest Image"),
                            ("S5P_SO2", "Sentinel-5P SO2 Latest Image"),
                            ("RISK_CALC", "Risk Calculation Status"),
                            ("DATA_SYNC", "Data Synchronization"),
                            ("SYS_HEALTH", "System Health"),
                        ],
                        db_index=True,
                        help_text="Type of status being tracked",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        default=dict,
                        help_text="Current status value (e.g., image date, task result)",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        auto_now=True, help_text="When this status was last updated"
                    ),
                ),
                (
                    "last_changed",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the value last changed"
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this status indicates a healthy state",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if status is unhealthy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Status",
                "verbose_name_plural": "System Statuses",
                "ordering": ["status_type"],
            },
        ),
    ]
