# Generated by Django 4.2 on 2025-12-11 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="include_ai_insights",
            field=models.BooleanField(
                default=False,
                help_text="Include AI-generated health recommendations (premium feature)",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Center point for location-based analysis",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="radius_km",
            field=models.FloatField(
                blank=True,
                help_text="Search radius in kilometers for location-based reports",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily Summary"),
                    ("WEEKLY", "Weekly Summary"),
                    ("MONTHLY", "Monthly Summary"),
                    ("DISTRICT", "District Detail"),
                    ("LOCATION", "Location-Based Trend Analysis"),
                    ("CUSTOM", "Custom Report"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reportsubscription",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily Summary"),
                    ("WEEKLY", "Weekly Summary"),
                    ("MONTHLY", "Monthly Summary"),
                    ("DISTRICT", "District Detail"),
                    ("LOCATION", "Location-Based Trend Analysis"),
                    ("CUSTOM", "Custom Report"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily Summary"),
                    ("WEEKLY", "Weekly Summary"),
                    ("MONTHLY", "Monthly Summary"),
                    ("DISTRICT", "District Detail"),
                    ("LOCATION", "Location-Based Trend Analysis"),
                    ("CUSTOM", "Custom Report"),
                ],
                max_length=20,
            ),
        ),
    ]
