# Generated by Django 4.2 on 2025-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_report_include_ai_insights_report_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Django-Q task ID for async report generation",
                max_length=100,
            ),
        ),
    ]
