# Generated by Django 5.2.8 on 2025-12-01 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("air_quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("GWR", "Geographically Weighted Regression"),
                            ("LINEAR", "Linear Regression"),
                            ("ENSEMBLE", "Ensemble"),
                        ],
                        default="GWR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Training"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("FAILED", "Failed"),
                        ],
                        default="TRAINING",
                        max_length=20,
                    ),
                ),
                (
                    "training_start_date",
                    models.DateField(help_text="Start date of training data period"),
                ),
                (
                    "training_end_date",
                    models.DateField(help_text="End date of training data period"),
                ),
                (
                    "training_samples",
                    models.IntegerField(
                        default=0,
                        help_text="Number of training samples used",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "training_stations",
                    models.IntegerField(
                        default=0,
                        help_text="Number of ground stations used",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bandwidth",
                    models.FloatField(
                        blank=True,
                        help_text="GWR bandwidth parameter (adaptive or fixed)",
                        null=True,
                    ),
                ),
                (
                    "kernel",
                    models.CharField(
                        default="bisquare",
                        help_text="GWR kernel function",
                        max_length=20,
                    ),
                ),
                (
                    "model_file",
                    models.CharField(
                        blank=True,
                        help_text="Path to serialized model file",
                        max_length=500,
                    ),
                ),
                (
                    "r_squared",
                    models.FloatField(
                        blank=True,
                        help_text="Coefficient of determination (R²)",
                        null=True,
                    ),
                ),
                (
                    "rmse",
                    models.FloatField(
                        blank=True, help_text="Root Mean Square Error", null=True
                    ),
                ),
                (
                    "mae",
                    models.FloatField(
                        blank=True, help_text="Mean Absolute Error", null=True
                    ),
                ),
                (
                    "bias",
                    models.FloatField(blank=True, help_text="Mean Bias", null=True),
                ),
                (
                    "cv_r_squared",
                    models.FloatField(
                        blank=True, help_text="Cross-validation R²", null=True
                    ),
                ),
                (
                    "cv_rmse",
                    models.FloatField(
                        blank=True, help_text="Cross-validation RMSE", null=True
                    ),
                ),
                (
                    "local_r_squared_min",
                    models.FloatField(
                        blank=True, help_text="Minimum local R² (GWR only)", null=True
                    ),
                ),
                (
                    "local_r_squared_max",
                    models.FloatField(
                        blank=True, help_text="Maximum local R² (GWR only)", null=True
                    ),
                ),
                (
                    "local_r_squared_mean",
                    models.FloatField(
                        blank=True, help_text="Mean local R² (GWR only)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the active model for predictions",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pollutant", "status"],
                        name="correction__polluta_9364dc_idx",
                    ),
                    models.Index(
                        fields=["pollutant", "is_active"],
                        name="correction__polluta_cd19b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalibrationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "ground_value",
                    models.FloatField(help_text="Ground station measurement"),
                ),
                (
                    "satellite_value",
                    models.FloatField(
                        help_text="Satellite-derived value at station location"
                    ),
                ),
                (
                    "corrected_value",
                    models.FloatField(
                        blank=True,
                        help_text="Model-predicted corrected value",
                        null=True,
                    ),
                ),
                (
                    "residual",
                    models.FloatField(
                        blank=True,
                        help_text="Prediction residual (ground - corrected)",
                        null=True,
                    ),
                ),
                (
                    "local_intercept",
                    models.FloatField(
                        blank=True, help_text="Local intercept coefficient", null=True
                    ),
                ),
                (
                    "local_slope",
                    models.FloatField(
                        blank=True, help_text="Local slope coefficient", null=True
                    ),
                ),
                (
                    "local_r_squared",
                    models.FloatField(blank=True, help_text="Local R²", null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_points",
                        to="air_quality.groundstation",
                    ),
                ),
                (
                    "correction_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_points",
                        to="correction.correctionmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["correction_model", "date"],
                        name="correction__correct_2d49b0_idx",
                    )
                ],
                "unique_together": {("correction_model", "station", "date")},
            },
        ),
        migrations.CreateModel(
            name="CorrectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "output_file",
                    models.CharField(
                        blank=True,
                        help_text="Path to corrected raster file",
                        max_length=500,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics of corrected raster (min, max, mean, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correction_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_runs",
                        to="correction.correctionmodel",
                    ),
                ),
                (
                    "raster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_runs",
                        to="air_quality.pollutantraster",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("correction_model", "raster")},
            },
        ),
    ]
