# Generated by Django 4.2 on 2025-12-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctionmodel",
            name="pollutant",
            field=models.CharField(
                choices=[
                    ("NO2", "NO2"),
                    ("SO2", "SO2"),
                    ("PM25", "PM25"),
                    ("PM10", "PM10"),
                    ("PM1", "PM1"),
                    ("CO", "CO"),
                    ("O3", "O3"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
