# Generated by Django 5.2.8 on 2025-12-01 14:54

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("air_quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvinceExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(db_index=True, max_length=100)),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_population", models.BigIntegerField(default=0)),
                ("concentration_mean", models.FloatField(blank=True, null=True)),
                ("aqi_mean", models.FloatField(blank=True, null=True)),
                ("exposure_index", models.FloatField(blank=True, null=True)),
                ("pop_good", models.BigIntegerField(default=0)),
                ("pop_moderate", models.BigIntegerField(default=0)),
                ("pop_usg", models.BigIntegerField(default=0)),
                ("pop_unhealthy", models.BigIntegerField(default=0)),
                ("pop_very_unhealthy", models.BigIntegerField(default=0)),
                ("pop_hazardous", models.BigIntegerField(default=0)),
                ("n_districts", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "rank"],
                "indexes": [
                    models.Index(
                        fields=["pollutant", "date"],
                        name="exposure_pr_polluta_a61aea_idx",
                    )
                ],
                "unique_together": {("province", "pollutant", "date")},
            },
        ),
        migrations.CreateModel(
            name="DistrictExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "total_population",
                    models.BigIntegerField(
                        default=0, help_text="Total population in district"
                    ),
                ),
                (
                    "concentration_mean",
                    models.FloatField(
                        blank=True,
                        help_text="Population-weighted mean concentration",
                        null=True,
                    ),
                ),
                ("concentration_min", models.FloatField(blank=True, null=True)),
                ("concentration_max", models.FloatField(blank=True, null=True)),
                ("concentration_std", models.FloatField(blank=True, null=True)),
                (
                    "aqi_mean",
                    models.FloatField(
                        blank=True, help_text="Population-weighted mean AQI", null=True
                    ),
                ),
                ("aqi_max", models.IntegerField(blank=True, null=True)),
                (
                    "pop_good",
                    models.BigIntegerField(
                        default=0, help_text="Population in Good AQI (0-50)"
                    ),
                ),
                (
                    "pop_moderate",
                    models.BigIntegerField(
                        default=0, help_text="Population in Moderate AQI (51-100)"
                    ),
                ),
                (
                    "pop_usg",
                    models.BigIntegerField(
                        default=0, help_text="Population in USG AQI (101-150)"
                    ),
                ),
                (
                    "pop_unhealthy",
                    models.BigIntegerField(
                        default=0, help_text="Population in Unhealthy AQI (151-200)"
                    ),
                ),
                (
                    "pop_very_unhealthy",
                    models.BigIntegerField(
                        default=0,
                        help_text="Population in Very Unhealthy AQI (201-300)",
                    ),
                ),
                (
                    "pop_hazardous",
                    models.BigIntegerField(
                        default=0, help_text="Population in Hazardous AQI (>300)"
                    ),
                ),
                (
                    "exposure_index",
                    models.FloatField(
                        blank=True,
                        help_text="Exposure index (0-500)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Rank among all districts (1=worst)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="air_quality.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "rank"],
                "indexes": [
                    models.Index(
                        fields=["pollutant", "date"],
                        name="exposure_di_polluta_2c16e7_idx",
                    ),
                    models.Index(
                        fields=["date", "rank"], name="exposure_di_date_3f1cc7_idx"
                    ),
                    models.Index(
                        fields=["district", "date"],
                        name="exposure_di_distric_e7ce7c_idx",
                    ),
                ],
                "unique_together": {("district", "pollutant", "date")},
            },
        ),
        migrations.CreateModel(
            name="Hotspot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Hotspot centroid", srid=4326
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, help_text="Hotspot boundary", null=True, srid=4326
                    ),
                ),
                (
                    "area_sq_km",
                    models.FloatField(
                        blank=True, help_text="Hotspot area in km²", null=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                (
                    "concentration_mean",
                    models.FloatField(help_text="Mean concentration in hotspot"),
                ),
                (
                    "concentration_max",
                    models.FloatField(help_text="Maximum concentration"),
                ),
                ("aqi_mean", models.IntegerField(help_text="Mean AQI in hotspot")),
                (
                    "affected_population",
                    models.BigIntegerField(
                        default=0, help_text="Estimated population in hotspot area"
                    ),
                ),
                (
                    "persistence_days",
                    models.IntegerField(
                        default=1, help_text="Number of consecutive days as hotspot"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affected_districts",
                    models.ManyToManyField(
                        blank=True, related_name="hotspots", to="air_quality.district"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-severity", "-affected_population"],
                "indexes": [
                    models.Index(
                        fields=["pollutant", "date"],
                        name="exposure_ho_polluta_ec7e10_idx",
                    ),
                    models.Index(
                        fields=["date", "severity"], name="exposure_ho_date_2e5c99_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NationalExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("NO2", "NO2"),
                            ("SO2", "SO2"),
                            ("PM25", "PM25"),
                            ("CO", "CO"),
                            ("O3", "O3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_population", models.BigIntegerField(default=0)),
                ("concentration_mean", models.FloatField(blank=True, null=True)),
                ("concentration_max", models.FloatField(blank=True, null=True)),
                ("aqi_mean", models.FloatField(blank=True, null=True)),
                ("exposure_index", models.FloatField(blank=True, null=True)),
                ("pop_good", models.BigIntegerField(default=0)),
                ("pop_moderate", models.BigIntegerField(default=0)),
                ("pop_usg", models.BigIntegerField(default=0)),
                ("pop_unhealthy", models.BigIntegerField(default=0)),
                ("pop_very_unhealthy", models.BigIntegerField(default=0)),
                ("pop_hazardous", models.BigIntegerField(default=0)),
                ("n_hotspots", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worst_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worst_exposure_days",
                        to="air_quality.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("pollutant", "date")},
            },
        ),
    ]
