# Generated by Django 4.2 on 2025-12-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality", "0002_add_new_station_reading_models"),
        ("exposure", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="districtexposure",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="nationalexposure",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="provinceexposure",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("satellite", "Satellite Only"),
                    ("ground", "Ground Only"),
                    ("fused", "Ground-Satellite Fusion"),
                    ("raster", "Corrected Raster"),
                ],
                default="satellite",
                help_text="Data source for this calculation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="max_aqi",
            field=models.FloatField(
                blank=True, help_text="Maximum AQI in district", null=True
            ),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="max_pm25",
            field=models.FloatField(
                blank=True, help_text="Maximum PM2.5 concentration", null=True
            ),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="mean_aqi",
            field=models.FloatField(
                blank=True,
                help_text="Combined AQI (worst of all pollutants)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="mean_pm25",
            field=models.FloatField(
                blank=True, help_text="Mean PM2.5 concentration (µg/m³)", null=True
            ),
        ),
        migrations.AddField(
            model_name="districtexposure",
            name="station_count",
            field=models.IntegerField(
                default=0, help_text="Number of ground stations in district"
            ),
        ),
        migrations.AddField(
            model_name="nationalexposure",
            name="district_count",
            field=models.IntegerField(
                default=0, help_text="Number of districts with data"
            ),
        ),
        migrations.AddField(
            model_name="nationalexposure",
            name="max_aqi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nationalexposure",
            name="mean_aqi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nationalexposure",
            name="mean_pm25",
            field=models.FloatField(
                blank=True,
                help_text="National population-weighted mean PM2.5",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nationalexposure",
            name="province_count",
            field=models.IntegerField(
                default=0, help_text="Number of provinces with data"
            ),
        ),
        migrations.AddField(
            model_name="provinceexposure",
            name="district_count",
            field=models.IntegerField(
                default=0, help_text="Number of districts with data"
            ),
        ),
        migrations.AddField(
            model_name="provinceexposure",
            name="max_aqi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provinceexposure",
            name="mean_aqi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provinceexposure",
            name="mean_pm25",
            field=models.FloatField(
                blank=True, help_text="Population-weighted mean PM2.5", null=True
            ),
        ),
        migrations.AddField(
            model_name="provinceexposure",
            name="worst_district",
            field=models.ForeignKey(
                blank=True,
                help_text="District with highest AQI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worst_province_days",
                to="air_quality.district",
            ),
        ),
        migrations.AlterField(
            model_name="districtexposure",
            name="pollutant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pollutant type (null for combined satellite data)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hotspot",
            name="pollutant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pollutant type (null for combined)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nationalexposure",
            name="pollutant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pollutant type (null for combined)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="provinceexposure",
            name="pollutant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pollutant type (null for combined)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="districtexposure",
            index=models.Index(
                fields=["data_source", "date"], name="exposure_di_data_so_323965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provinceexposure",
            index=models.Index(
                fields=["province", "date"], name="exposure_pr_provinc_b513e1_idx"
            ),
        ),
    ]
