# Generated by Django 4.2 on 2025-12-10 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataFreshness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                (
                    "last_check",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("S5P_NO2", "Sentinel-5P NO2"),
                            ("WORLDPOP", "WorldPop Population"),
                            ("OPENAQ_LOCAL", "OpenAQ Local Data"),
                            ("GEE_SERVICE", "Google Earth Engine Service"),
                            ("RISK_CALC", "Risk Map Calculation"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "last_available_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Latest data timestamp available from source",
                        null=True,
                    ),
                ),
                (
                    "last_successful_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time data was successfully retrieved",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional source-specific information",
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the data source is currently operational",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Freshness Status",
                "verbose_name_plural": "Data Freshness Statuses",
                "ordering": ["-last_check"],
            },
        ),
    ]
