# Generated by Django 4.2 on 2025-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="premium_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Premium subscription expiry date (null for lifetime/basic)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_tier",
            field=models.CharField(
                choices=[("BASIC", "Basic"), ("PREMIUM", "Premium")],
                default="BASIC",
                help_text="User subscription tier (BASIC or PREMIUM)",
                max_length=10,
            ),
        ),
    ]
