# Generated by Django 5.2.8 on 2025-12-01 14:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("air_quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("DISTRICT", "District Detail"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "pollutants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        size=None,
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=100)),
                (
                    "include_national",
                    models.BooleanField(
                        default=True, help_text="Include national summary"
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("DISTRICT", "District Detail"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "html_template",
                    models.TextField(
                        help_text="Jinja2/Django template for report body"
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True, help_text="CSS styles for PDF rendering"
                    ),
                ),
                ("header_template", models.TextField(blank=True)),
                ("footer_template", models.TextField(blank=True)),
                (
                    "page_size",
                    models.CharField(
                        default="A4",
                        help_text="PDF page size (A4, Letter, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                        default="portrait",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["report_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("DISTRICT", "District Detail"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "pollutants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        help_text="Pollutants included in report",
                        size=None,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("province", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("HTML", "HTML"), ("JSON", "JSON")],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated report file",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the report file will be deleted",
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="air_quality.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
